from enum import Enum
from typing import Union, Iterable

class StrEnum(str, Enum):
    @classmethod
    def to_list(cls: Union[Enum, Iterable]):
        return [element.value for element in cls]

class UrlFactory(StrEnum):
    BWIN = 'https://sports.bwin.es/es/sports/eventos/{id}'
    UNIBET = 'https://www.888sport.es/#/event/live/{id}'
    
class BetMap(StrEnum):
    TROPHY_WINNER = 'Trophy winner'
    HIGHER_IN_LEAGUE = 'Higher in league'
    TOTAL_GOALS_SECOND_HALF_OU = 'Total goals in second half'
    TOTAL_GOALS_FIRST_HALF_OU = 'Total goals in first half'
    TOTAL_GOALS_EXTRA_TIME_OU = 'Total Goals O/U - Extra Time'
    GIVE_ASSIST_YN = 'Give an assist HEAD TO HEAD'
    OWN_GOAL_YN = 'Own goal YES/NO'
    TOTAL_GOALS_OE = 'Total goals ODD/EVEN'
    ONE_GOL_WIN_EXACT = 'TEAM1/TEAM2 Win by exactly 1 goal'
    TWO_GOL_WIN_EXACT = 'TEAM1/TEAM2 Win by exactly 2 goal'
    THREE_GOL_WIN_EXACT = 'TEAM1/TEAM2 Win by exactly 3 goal'
    FOUR_GOL_WIN_EXACT = 'TEAM1/TEAM2 Win by exactly 4 goal'
    FIVE_GOL_WIN_EXACT = 'TEAM1/TEAM2 Win by exactly 5 goal'
    TOTAL_CORNERS_OE = 'Total corners ODD/EVEN'
    RED_CARD_GIVEN_YN ='Red card YES/NO'
    TOTAL_GOALS_OU = 'Total goals OVER/UNDER'
    DRAW_NO_BET_SECOND_HALF = 'Draw no bet in second half'
    FIRST_GOAL_NO_GOAL_NO_BET_MATCH = 'First Goal. No Goal, No Bet Match'
    HANDICAP = 'Handicap'
    PENALTY_KICK_AWARDED = 'Penalty kick YES/NO'
    PENALTY_MISS = 'To miss a penalty'
    SCORE_FROM_FREE_KICK_HH = 'To score from a direct free kick head to head'
    TOTAL_GOALS_FIRST_HALF_OE = 'Total goals in first half ODD/EVEN'
    SCORE_IN_SECOND_HALF = 'To score during 2nd Half Head to Head'
    BOTH_TEAMS_SCORE_SECOND_HALF_YN = 'Both teams to score in second half'
    TOTAL_CORNERS_FIRST_HALF = 'Total corners in first half OVER/UNDER'
    TOTAL_CORNERS_SECOND_HALF = 'Total corners in second half OVER/UNDER'
    TOTAL_CORNERS_OU = 'Total corners OVER/UNDER'
    DRAW_NO_BET_FIRST_HALF = 'Draw no bet in first half'
    DRAW_BOTH_TEAMS_SCORE_YN = 'Both teams to score DRAW YES/NO'
    GOAL_BOTH_HALVES_YN = 'Goal in both halves YES/NO'
    SCORE_FROM_HEADER = 'Score from a header HEAD TO HEAD'
    SCORE_FIRST_HALF_HH = 'Score during first half head to head'
    TOTAL_CARDS_OU = 'Total cards OVER/UNDER'
    TOTAL_SHOTS_ON_TARGET_OU = 'Total Shots on Target Over/Under'
    CARDS_HANDICAP = 'Cards handicap'
    DOUBLE_CHANCE = 'Double chance'
    DOUBLE_CHANCE_FIRST_HALF = 'Double Chance - 1st Half Double Chance'
    DOUBLE_CHANCE_SECOND_HALF = 'Double Chance - 2nd Half Double Chance'
    GET_CARD = 'Get card'
    QUALIFY_NEXT_ROUND = 'Qualify to next round'
    NEXT_GOAL_NO_GOAL_NO_BET = 'Next goal no goal no bet'
    LAST_GOAL_NO_GOAL_NO_BET = 'Last Goal no Goal no bet match'
    HANDICAP_FIRST_HALF = 'Handicap in first half'
    TOTAL_GOALS_FIRST_HALF = 'Total goals in first half OVER/UNDER'
    GOAL_SCORED_FROM_0000_TO_1500 = 'Goal scored FROM 00:00 TO 15:00'
    GOAL_SCORED_FROM_0000_TO_3000 = 'Goal scored FROM 00:00 TO 30:00'
    GOAL_SCORED_FROM_3000_TO_4500 = 'Goal scored FROM 30:00 TO 45:00'
    TOTAL_CORNERS_FROM_7500_TO_9000 = 'Corners FROM 75:00 TO Full time'
    TOTAL_CORNERS_FROM_6000_TO_7500 = 'Corners FROM 60:00 TO 75:00'
    TOTAL_CORNERS_FROM_4500_TO_6000 = 'Corners FROM 45:00 TO 60:00'
    TOTAL_CORNERS_FROM_3000_TO_4500 = 'Corners FROM 30:00 TO 45:00'
    TOTAL_CORNERS_FROM_1500_TO_3000 = 'Corners FROM 15:00 TO 30:00'
    TOTAL_CORNERS_FROM_0000_TO_1500 = 'Corners FROM 00:00 TO 15:00'
    TOTAL_GOALS_FROM_1500_TO_3000 = 'Total Goals between 15:01 min. and 30:00'
    TOTAL_GOALS_FROM_7500_TO_9000 = 'Total Goals between 75:01 min. and full Time'
    TOTAL_GOALS_FROM_3000_TO_4500 = 'Total Goals between 15:01 min. and half Time'
    TOTAL_GOALS_FROM_0000_TO_1500 = 'Total Goals between 00:01 min. and 15:00'
    TOTAL_GOALS_FROM_6000_TO_7500 = 'Total Goals between 60:01 min. and 75:00'
    TOTAL_GOALS_FROM_4500_TO_6000 = 'Total Goals between 45:01 min. and 60:00'

    ASIAN_HANDICAP_FIRST_HALF_00_AH = 'Asian handicap in first half Asian handicap'
    ASIAN_TOTAL_FIRST_HALF_OU = 'Asian total in first half Asian OVER/UNDER'
    ASIAN_HANDICAP_FIRST_HALF_ASIAN_HANDICAP = 'Asian handicap in first half Asian handicap'
    ASIAN_TOTAL_OU = 'Asian total OVER/UNDER'
    ASIAN_HANDICAP = 'Asian handicap'
    ASIAN_HANDICAP_00 = 'Asian handicap 0-0'
    
    TEAM1_NO_BET = 'X OR 2'
    TEAM2_NO_BET = '1 OR X'
    DRAW_NO_BET = '1 OR 2'

    TEAM1_TO_SCORE_FROM_PENALTY = 'Team 1 to score from a penalty Yes/No'
    TEAM1_AWARDED_PENALTY = 'Team 1 to be awarded a penalty Yes/No'
    TEAM1_WIN_TO_NIL = 'TEAM 1 to win to nil'
    TEAM1_SCORES_BOTH_HALVES = 'TEAM 1 to score in both halves'
    TEAM1_TO_SCORE_FIRST_AND_WIN = 'Team1 to score first and win'
    TEAM1_TO_SCORE_FIRST_HALF = 'Team 1 To Score - 1st Half Yes/No'
    TEAM1_TO_WIN_AFTER_GOAL_BEHIND = 'Team 1 to win after being a goal behind Yes/No '
    TEAM1_GIVEN_RED_CARD ='Red card TEAM 1 YES/NO'
    TEAM1_TOTAL_CORNERS_OU = 'Total corners TEAM 1 OVER/UNDER'
    TEAM1_TOTAL_GOALS_FIRST_HALF = 'Total goals TEAM 1 in first half OVER/UNDER'
    TEAM1_TOTAL_GOALS_SECOND_HALF = 'Total goals TEAM 1 in second half OVER/UNDER'
    TEAM1_TOTAL_GOALS_OU = 'Total goals TEAM 1 OVER/UNDER'
    TEAM1_TOTAL_GOALS_OE = 'Total goals TEAM 1'
    TEAM1_WIN_A_HALF = 'TEAM 1 win a half YES/NO'
    TEAM1_SCORES_YN = 'TEAM 1 SCORES YES/NO'
    TEAM1_WIN_BOTH_SCORE_YN = 'Both teams score TEAM 1 WIN'
    TEAM1_TOTAL_GOALS_SECOND_HALF_OU = 'Total goals TEAM 1 in second half OVER/UNDER'
    TEAM1_TOTAL_CARDS_OU = 'Total cards TEAM 1 OVER/UNDER'
    TEAM1_TOTAL_SHOTS_ON_TARGET_OU = 'Total Shots on Target by Team 1 Over/Under'
    TEAM1_WIN_BOTH_HALVES = 'TEAM 1 win both halves'
    TEAM_1_TOTAL_GOAL_SCORED_FROM_3000_TO_4500 = 'TEAM 1 total goal scored FROM 30:00 TO 45:00'
    TEAM_1_TOTAL_GOAL_SCORED_FROM_7500_TO_9000 = 'TEAM 1 total goal scored FROM 75:00 TO 90:00'
    TEAM_1_TOTAL_GOAL_SCORED_FROM_6000_TO_7500 = 'TEAM 1 total goal scored FROM 60:00 TO 75:00'
    TEAM_1_TOTAL_GOAL_SCORED_FROM_4500_TO_6000 = 'TEAM 1 total goal scored FROM 45:00 TO 60:00'
    TEAM_1_TOTAL_GOAL_SCORED_FROM_0000_TO_1500 = 'TEAM 1 total goal scored FROM 00:00 TO 15:00'
    TEAM_1_TOTAL_GOAL_SCORED_FROM_1500_TO_3000 = 'TEAM 1 total goal scored FROM 15:00 TO 30:00'


    TEAM2_WIN_BOTH_HALVES_YN = 'TEAM 2 to win both halves YES/NO'
    TEAM2_RED_CARD_YN = 'TEAM 2 red card YES/NO'
    TEAM2_SCORE_YN = 'TEAM 2 score YES/NO'
    TEAM2_SCORE_FROM_PENALTY = 'Team 2 to score from a penalty Yes/No'
    TEAM2_AWARDED_PENALTY = 'Team 2 to be awarded a penalty Yes/No'
    TEAM2_WIN_A_HALF_YN = 'TEAM 2 win a half YES/NO'
    TEAM2_WIN_BOTH_TEAMS_SCORE_YN = 'Both teams to score TEAM 2 WIN'
    TEAM2_TOTAL_CORNERS_OU = 'Total corners TEAM 2 OVER/UNDER'
    TEAM2_TOTAL_GOALS_OU = 'Total goals TEAM 2 OVER/UNDER'
    TEAM2_TO_WIN_AFTER_GOAL_BEHIND = 'Team 2 to win after being a goal behind Yes/No '
    TEAM2_TOTAL_GOALS_FIRST_HALF_OU = 'Total goals TEAM 2 in first half OVER/UNDER'
    TEAM2_SCORE_BOTH_HALVES_YN = 'TEAM 2 to score in both halves YES/NO'
    TEAM2_SCORE_FIRST_HALF_YN = 'TEAM 2 score in first half YES/NO'
    TEAM2_SCORE_FIRST_HALF_AND_WIN_YN = 'TEAM 2 score in first half and win YES/NO'
    TEAM2_WIN_TO_NIL = 'TEAM 2 to win to nil YES/NO'
    TEAM2_TOTAL_CARDS_OU = 'Total cards TEAM 2 OVER/UNDER'
    TEAM2_TOTAL_GOALS_OE = 'Total goals TEAM 2 ODD/EVEN'
    TEAM2_TOTAL_SHOTS_ON_TARGET_OU = 'Total Shots on Target by Team 2 Over/Under'
    TEAM2_TOTAL_GOALS_SECOND_HALF_OU = 'Total goals TEAM 2 in second half OVER/UNDER'
    TEAM2_TOTAL_GOALS_FROM_45_TO_60_MIN = 'Total goals TEAM 2 FROM 45:00 TO 60:00'
    TEAM2_TOTAL_GOALS_FROM_00_TO_15_MIN = 'Total goals TEAM 2 FROM 00:00 TO 15:00'
    TEAM2_TOTAL_GOALS_FROM_30_TO_45_MIN = 'Total goals TEAM 2 FROM 30:00 TO 45:00'
    TEAM2_TOTAL_GOALS_FROM_15_TO_30_MIN = 'Total goals TEAM 2 FROM 15:00 TO 30:00'
    TEAM2_TOTAL_GOALS_FROM_75_TO_90_MIN = 'Total goals TEAM 2 FROM 75:00 TO Full time'
    TEAM2_TOTAL_GOALS_FROM_60_TO_75_MIN = 'Total goals TEAM 2 FROM 60:00 TO 75:00'


    BOTH_TEAMS_SCORE_BOTH_HALVES_YN = 'Both teams to score in both halves YES/NO'
    BOTH_TEAMS_SCORE_YN = 'Both teams to score YES/NO'
    BOTH_TEAMS_SCORE_FIRST_HALF_YN = 'Both teams to score in first half YES/NO'
    
    SCORE_AND_ASSIST = 'Score and assist HEAD TO HEAD'
    SCORE_AND_BOOKED = 'To score & get booked Head to Head'
